"""
Few-shot examples for the LLM Judge.

Examples are loaded from judge_examples.json, which is generated by
running: python -m src.LeadEvolver.judge.extract_judge_examples
"""

import json
from pathlib import Path
from typing import List, Dict


# Path to the JSON file containing judge examples
EXAMPLES_JSON_PATH = Path(__file__).parent / "judge_examples.json"

# Cache for loaded examples
_cached_examples: List[Dict] | None = None


def get_judge_examples() -> List[Dict]:
    """
    Load and return the list of judge examples from JSON.

    Returns:
        List of example dicts with keys: name, username, context, icp_match, rationale
    """
    global _cached_examples

    if _cached_examples is not None:
        return _cached_examples

    if not EXAMPLES_JSON_PATH.exists():
        raise FileNotFoundError(
            f"Judge examples not found at {EXAMPLES_JSON_PATH}. "
            "Run: python -m src.LeadEvolver.judge.extract_judge_examples"
        )

    with open(EXAMPLES_JSON_PATH, 'r', encoding='utf-8') as f:
        _cached_examples = json.load(f)

    return _cached_examples


def format_example_for_prompt(example: Dict) -> str:
    """Format a single example for inclusion in the judge prompt."""
    return f"""=== EXAMPLE ===
Lead Name: {example['name']}

Lead Context:
{example['context']}

Classification: {example['icp_match']}
Rationale: {example['rationale']}
=== END EXAMPLE ==="""


def get_formatted_examples() -> str:
    """Return all examples formatted for the judge prompt."""
    examples = get_judge_examples()
    formatted = [format_example_for_prompt(ex) for ex in examples]
    return "\n\n".join(formatted)
